deployment:
  tasks:
    - export DEPLOYPATH=/home/brgyhywz/public_html/
    - mkdir -p "$DEPLOYPATH"
    - find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.cpanel.yml' -exec cp -R {} "$DEPLOYPATH" \;