CREATE TABLE IF NOT EXISTS `disconnection_notices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `billing_id` int(11) DEFAULT NULL,
  `notice_type` enum('first_warning','final_notice','disconnection_order') NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `amount_due` decimal(10,2) NOT NULL,
  `overdue_days` int(11) NOT NULL,
  `due_date` date NOT NULL,
  `grace_period_days` int(11) NOT NULL DEFAULT 7,
  `disconnection_date` date DEFAULT NULL,
  `status` enum('pending','sent','acknowledged','resolved','expired') NOT NULL DEFAULT 'pending',
  `created_by` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sent_at` timestamp NULL DEFAULT NULL,
  `acknowledged_at` timestamp NULL DEFAULT NULL,
  `resolved_at` timestamp NULL DEFAULT NULL,
  `resolution_notes` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  KEY `billing_id` (`billing_id`),
  KEY `created_by` (`created_by`),
  KEY `status` (`status`),
  KEY `notice_type` (`notice_type`),
  CONSTRAINT `disconnection_notices_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `client_list` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `disconnection_notices_ibfk_2` FOREIGN KEY (`billing_id`) REFERENCES `billing_list` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `disconnection_notices_ibfk_3` FOREIGN KEY (`created_by`) REFERENCES `admin` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 