<?php
session_start();
if (!isset($_SESSION['admin_id'])) {
    header("Location: adminlogin.php");
    exit();
}

include 'db.php';
include 'disconnection_logic.php';

$success_message = '';
$error_message = '';

// Handle form actions
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    $admin_id = $_SESSION['admin_id'];
    $selected_billing_cycle_id = isset($_POST['billing_cycle_id']) && $_POST['billing_cycle_id'] !== '' 
        ? intval($_POST['billing_cycle_id']) 
        : null;
    
    switch ($_POST['action']) {
        case 'auto_generate':
            try {
                $generated_count = autoGenerateDisconnectionNotices($admin_id, $selected_billing_cycle_id);
                $success_message = "Successfully generated {$generated_count} disconnection notices.";
            } catch (Exception $e) {
                $error_message = "Error generating notices: " . $e->getMessage();
            }
            break;
            
        case 'send_notice':
            $notice_id = intval($_POST['notice_id']);
            $stmt = $conn->prepare("UPDATE disconnection_notices SET status = 'sent', sent_at = NOW() WHERE id = ?");
            $stmt->bind_param("i", $notice_id);
            if ($stmt->execute()) {
                $success_message = "Notice sent successfully.";
            } else {
                $error_message = "Error sending notice.";
            }
            break;
            
        case 'resolve_notice':
            $notice_id = intval($_POST['notice_id']);
            $resolution_notes = trim($_POST['resolution_notes']);
            $stmt = $conn->prepare("UPDATE disconnection_notices SET status = 'resolved', resolved_at = NOW(), resolution_notes = ? WHERE id = ?");
            $stmt->bind_param("si", $resolution_notes, $notice_id);
            if ($stmt->execute()) {
                $success_message = "Notice marked as resolved.";
            } else {
                $error_message = "Error resolving notice.";
            }
            break;
            
        case 'create_manual':
            $client_id = intval($_POST['client_id']);
            $notice_type = $_POST['notice_type'];
            $amount_due = floatval($_POST['amount_due']);
            $overdue_days = intval($_POST['overdue_days']);
            $due_date = $_POST['due_date'];
            $custom_description = trim($_POST['custom_description']);
            
            // Create manual notice
            $notice_data = [
                'type' => $notice_type,
                'bill' => ['id' => null, 'due_date' => $due_date],
                'total_amount' => $amount_due,
                'overdue_days' => $overdue_days,
                'reason' => 'Manual notice created by admin'
            ];
            
            if (!empty($custom_description)) {
                $notice_content = ['title' => 'Water Service Notice', 'description' => $custom_description];
                // Override generated content with custom description
            }
            
            if (createDisconnectionNotice($client_id, $notice_data, $admin_id)) {
                $success_message = "Manual disconnection notice created successfully.";
            } else {
                $error_message = "Error creating manual notice.";
            }
            break;
    }
}

// Get filter parameters
$status_filter = isset($_GET['status']) ? $_GET['status'] : '';
$type_filter = isset($_GET['type']) ? $_GET['type'] : '';
$billing_cycle_filter = isset($_GET['billing_cycle_id']) ? intval($_GET['billing_cycle_id']) : 0;
$search = isset($_GET['search']) ? $conn->real_escape_string($_GET['search']) : '';

// Build WHERE clause for filters
$where_conditions = [];
$params = [];
$types = '';

if ($search) {
    $where_conditions[] = "(cl.firstname LIKE ? OR cl.lastname LIKE ? OR cl.code LIKE ?)";
    $search_param = "%$search%";
    $params[] = $search_param;
    $params[] = $search_param;
    $params[] = $search_param;
    $types .= 'sss';
}

if ($status_filter) {
    $where_conditions[] = "dn.status = ?";
    $params[] = $status_filter;
    $types .= 's';
}

if ($type_filter) {
    $where_conditions[] = "dn.notice_type = ?";
    $params[] = $type_filter;
    $types .= 's';
}

if ($billing_cycle_filter) {
    $where_conditions[] = "bl.billing_cycle_id = ?";
    $params[] = $billing_cycle_filter;
    $types .= 'i';
}

$where_clause = $where_conditions ? 'WHERE ' . implode(' AND ', $where_conditions) : '';

// Get disconnection notices with client and billing cycle information
$sql = "SELECT dn.*, 
               cl.firstname, cl.lastname, cl.contact, cl.address, cl.code as client_code,
               a.username as created_by_username,
               bl.billing_cycle_id,
               bc.cycle_name
        FROM disconnection_notices dn
        JOIN client_list cl ON dn.client_id = cl.id
        JOIN admin a ON dn.created_by = a.id
        LEFT JOIN billing_list bl ON dn.billing_id = bl.id
        LEFT JOIN billing_cycles bc ON bl.billing_cycle_id = bc.id
        {$where_clause}
        ORDER BY dn.created_at DESC";

if ($types) {
    $stmt = $conn->prepare($sql);
    $stmt->bind_param($types, ...$params);
    $stmt->execute();
    $notices = $stmt->get_result();
} else {
    $notices = $conn->query($sql);
}

// Get statistics
$stats_sql = "SELECT 
                COUNT(*) as total_notices,
                SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending_notices,
                SUM(CASE WHEN status = 'sent' THEN 1 ELSE 0 END) as sent_notices,
                SUM(CASE WHEN status = 'resolved' THEN 1 ELSE 0 END) as resolved_notices,
                SUM(CASE WHEN notice_type = 'disconnection_order' AND status IN ('pending', 'sent') THEN 1 ELSE 0 END) as critical_notices,
                SUM(amount_due) as total_amount_due
              FROM disconnection_notices";
$stats = $conn->query($stats_sql)->fetch_assoc();

// Get clients for manual notice creation
$clients_sql = "SELECT id, firstname, lastname, code FROM client_list WHERE status = 1 ORDER BY lastname, firstname";
$clients = $conn->query($clients_sql);

// Get billing cycles for filters
$cycles_sql = "SELECT id, cycle_name, start_date, end_date FROM billing_cycles ORDER BY start_date DESC";
$billing_cycles = $conn->query($cycles_sql);

// Get clients needing notices for auto-generation preview (respect billing cycle filter)
$clients_needing_notices = getAllClientsNeedingNotices($billing_cycle_filter ?: null);
?>

<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Disconnection Notices - Water Billing System</title>
    
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Google Fonts & Icons -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet" />

    <style>
    :root[data-theme="light"] {
        --bg-color: #f8f9fa;
        --sidebar-bg: #fff;
        --text-color: #333;
        --card-bg: #fff;
        --border-color: #dee2e6;
        --hover-bg: #f0f2f5;
        --hover-text: #007bff;
        --muted-text: #6c757d;
        --card-text: #333;
        --table-header-bg: #f8f9fa;
        --table-header-text: #333;
        --table-cell-text: #333;
        --table-bg: #fff;
    }

    :root[data-theme="dark"] {
        --bg-color: #1a1d21;
        --sidebar-bg: #242529;
        --text-color: #e4e6eb;
        --card-bg: #2d2f34;
        --border-color: #393b40;
        --hover-bg: #393b40;
        --hover-text: #4e9eff;
        --muted-text: #a0a0a0;
        --card-text: #e4e6eb;
        --table-header-bg: #242529;
        --table-header-text: #e4e6eb;
        --table-cell-text: #e4e6eb;
        --table-bg: #2d2f34;
    }

    body {
        font-family: 'Open Sans', sans-serif;
        background-color: var(--bg-color);
        color: var(--text-color);
        transition: background-color 0.3s, color 0.3s;
    }

    .sidebar {
        height: 100vh;
        background-color: var(--sidebar-bg);
        border-right: 1px solid var(--border-color);
        padding-top: 20px;
        position: fixed;
        width: 250px;
        display: flex;
        flex-direction: column;
    }

    .sidebar-header {
        padding: 20px;
        margin-bottom: 20px;
        text-align: center;
        background-color: var(--card-bg);
        border: 1px solid var(--border-color);
        margin: 0 20px 20px;
        border-radius: 12px;
        transition: background-color 0.3s, border-color 0.3s;
    }

    /* Prevent logo from being affected by dark mode filters */
    .sidebar-header img {
        filter: none !important;
        opacity: 1 !important;
    }

    html[data-theme="dark"] .sidebar-header img,
    [data-theme="dark"] .sidebar-header img {
        filter: none !important;
        opacity: 1 !important;
        mix-blend-mode: normal !important;
    }

    /* Keep sidebar-header background light in dark mode for logo visibility */
    html[data-theme="dark"] .sidebar-header,
    [data-theme="dark"] .sidebar-header {
        background-color: #fff !important;
    }

    .nav-content {
        flex: 1;
        overflow-y: auto;
    }

    .sidebar-footer {
        padding: 20px;
        border-top: 1px solid var(--border-color);
        margin-top: auto;
    }

    .sidebar a {
        padding: 12px 20px;
        display: flex;
        align-items: center;
        color: var(--text-color);
        font-weight: 600;
        text-decoration: none;
        border-radius: 12px;
        margin: 0 8px 8px;
        transition: all 0.3s ease;
    }

    .sidebar a i {
        min-width: 24px;
        margin-right: 10px;
        text-align: center;
    }

    .sidebar a:hover,
    .sidebar a.active {
        background-color: var(--hover-bg);
        color: var(--hover-text);
    }

    .main-content {
        margin-left: 250px;
        padding: 30px;
    }

    .card-soft {
        border-radius: 15px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        border: none;
        background-color: var(--card-bg);
        color: var(--card-text);
    }

    .stat-card {
        border: none;
        border-radius: 18px;
        overflow: hidden;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
        background: linear-gradient(135deg, #ffffff, #f3f4ff);
        color: var(--card-text);
        box-shadow: 0 6px 18px rgba(15, 23, 42, 0.12);
    }

    .stat-card .card-body {
        padding: 18px 20px;
    }

    .stat-card:hover {
        transform: translateY(-3px);
        box-shadow: 0 10px 30px rgba(15, 23, 42, 0.18);
    }

    .stat-card.pending {
        background: linear-gradient(135deg, #fff7e6 0%, #ffe3b3 100%);
    }
    .stat-card.sent {
        background: linear-gradient(135deg, #e3f2fd 0%, #bbdefb 100%);
    }
    .stat-card.critical {
        background: linear-gradient(135deg, #ffe5e9 0%, #ffb3c0 100%);
    }
    .stat-card.resolved {
        background: linear-gradient(135deg, #e3f9e5 0%, #b2f2bb 100%);
    }

    /* Dark mode variants for stat cards */
    html[data-theme="dark"] .stat-card,
    [data-theme="dark"] .stat-card {
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.6);
        color: #e4e6eb;
    }

    html[data-theme="dark"] .stat-card.pending,
    [data-theme="dark"] .stat-card.pending {
        background: linear-gradient(135deg, #3b2c02 0%, #7c5e10 100%);
    }
    html[data-theme="dark"] .stat-card.sent,
    [data-theme="dark"] .stat-card.sent {
        background: linear-gradient(135deg, #0b2545 0%, #123e7c 100%);
    }
    html[data-theme="dark"] .stat-card.critical,
    [data-theme="dark"] .stat-card.critical {
        background: linear-gradient(135deg, #4b0f19 0%, #a3122f 100%);
    }
    html[data-theme="dark"] .stat-card.resolved,
    [data-theme="dark"] .stat-card.resolved {
        background: linear-gradient(135deg, #083828 0%, #0f5132 100%);
    }

    .table {
        color: var(--table-cell-text);
        background-color: var(--table-bg);
        border-collapse: separate;
        border-spacing: 0 6px;
    }

    .table thead th {
        background: linear-gradient(135deg, #f1f5f9 0%, #e2e8f0 100%);
        color: var(--table-header-text);
        border-bottom: none;
        border-top: none;
        font-size: 0.85rem;
        text-transform: uppercase;
        letter-spacing: 0.04em;
    }

    html[data-theme="dark"] .table thead th,
    [data-theme="dark"] .table thead th {
        background: linear-gradient(135deg, #111827 0%, #1f2937 100%);
        color: #e5e7eb;
    }

    .table tbody tr {
        box-shadow: 0 2px 8px rgba(15, 23, 42, 0.08);
        border-radius: 12px;
    }

    .table tbody tr td:first-child {
        border-top-left-radius: 12px;
        border-bottom-left-radius: 12px;
    }

    .table tbody tr td:last-child {
        border-top-right-radius: 12px;
        border-bottom-right-radius: 12px;
    }

    .table td, .table th {
        background-color: var(--table-bg);
        border-color: transparent;
        color: var(--table-cell-text);
        vertical-align: middle;
    }

    /* Row accents based on status */
    .notice-row-pending {
        border-left: 4px solid #ffc107;
    }
    .notice-row-sent {
        border-left: 4px solid #0d6efd;
    }
    .notice-row-resolved {
        border-left: 4px solid #198754;
    }
    .notice-row-expired {
        border-left: 4px solid #6c757d;
    }

    /* Dark mode table improvements */
    html[data-theme="dark"] .table tbody td,
    [data-theme="dark"] .table tbody td {
        color: var(--text-color) !important;
    }

    html[data-theme="dark"] .table tbody td strong,
    [data-theme="dark"] .table tbody td strong {
        color: var(--text-color) !important;
    }

    /* Dark mode text-muted improvements */
    html[data-theme="dark"] .text-muted,
    [data-theme="dark"] .text-muted {
        color: #b0b0b0 !important;
    }

    html[data-theme="dark"] .table .text-muted,
    [data-theme="dark"] .table .text-muted {
        color: #b0b0b0 !important;
    }

    html[data-theme="dark"] .card-subtitle.text-muted,
    [data-theme="dark"] .card-subtitle.text-muted {
        color: #b0b0b0 !important;
    }

    /* Dark mode badge improvements */
    html[data-theme="dark"] .badge.bg-warning,
    [data-theme="dark"] .badge.bg-warning {
        background-color: #ffc107 !important;
        color: #000 !important;
    }

    html[data-theme="dark"] .badge.bg-danger,
    [data-theme="dark"] .badge.bg-danger {
        background-color: #dc3545 !important;
        color: #fff !important;
    }

    html[data-theme="dark"] .badge.bg-dark,
    [data-theme="dark"] .badge.bg-dark {
        background-color: #495057 !important;
        color: #fff !important;
    }

    html[data-theme="dark"] .badge.bg-info,
    [data-theme="dark"] .badge.bg-info {
        background-color: #0dcaf0 !important;
        color: #000 !important;
    }

    html[data-theme="dark"] .badge.bg-primary,
    [data-theme="dark"] .badge.bg-primary {
        background-color: #0d6efd !important;
        color: #fff !important;
    }

    html[data-theme="dark"] .badge.bg-success,
    [data-theme="dark"] .badge.bg-success {
        background-color: #198754 !important;
        color: #fff !important;
    }

    html[data-theme="dark"] .badge.bg-secondary,
    [data-theme="dark"] .badge.bg-secondary {
        background-color: #6c757d !important;
        color: #fff !important;
    }

    /* Dark mode text-danger improvements */
    html[data-theme="dark"] .text-danger,
    [data-theme="dark"] .text-danger {
        color: #ff6b6b !important;
    }

    html[data-theme="dark"] .table .text-danger,
    [data-theme="dark"] .table .text-danger {
        color: #ff6b6b !important;
    }

    .theme-switch-wrapper {
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 10px;
        border-radius: 10px;
        margin: 10px 20px;
        background-color: var(--hover-bg);
    }

    .theme-switch-wrapper i {
        margin: 0 5px;
        color: var(--text-color);
    }

    .theme-switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
        margin: 0 10px;
    }

    .theme-switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        transition: .4s;
        border-radius: 34px;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 26px;
        width: 26px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        transition: .4s;
        border-radius: 50%;
    }

    input:checked + .slider {
        background-color: #2196F3;
    }

    input:checked + .slider:before {
        transform: translateX(26px);
    }

    .btn-outline-primary {
        color: var(--hover-text);
        border-color: var(--hover-text);
    }

    .btn-outline-primary:hover {
        background-color: var(--hover-text);
        border-color: var(--hover-text);
        color: #fff;
    }

    .modal-content {
        background-color: var(--card-bg);
        color: var(--text-color);
        border: 1px solid var(--border-color);
    }

    .modal-header {
        background-color: var(--sidebar-bg);
        border-bottom: 1px solid var(--border-color);
        color: var(--text-color);
    }

    .modal-footer {
        background-color: var(--sidebar-bg);
        border-top: 1px solid var(--border-color);
    }

    .form-control, .form-select {
        background-color: var(--sidebar-bg);
        border-color: var(--border-color);
        color: var(--text-color);
    }

    .form-control:focus, .form-select:focus {
        background-color: var(--sidebar-bg);
        border-color: var(--hover-text);
        color: var(--text-color);
        box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
    }

    .btn-close {
        filter: invert(1);
    }

    [data-theme="light"] .btn-close {
        filter: none;
    }

    /* Filters card */
    .filters-card {
        border-radius: 16px;
        border: none;
        box-shadow: 0 4px 14px rgba(15, 23, 42, 0.16);
    }

    .filters-card .form-label {
        font-size: 0.8rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        color: var(--muted-text);
    }

    /* Responsive */
    @media (max-width: 991.98px) {
        .sidebar {
            position: fixed;
            top: 0;
            left: 0;
            height: 100vh;
            width: 250px;
            background-color: var(--sidebar-bg);
            border-right: 1px solid var(--border-color);
            transform: translateX(-250px);
            transition: transform 0.3s ease;
            z-index: 1050;
            display: block;
        }
        .sidebar.open {
            transform: translateX(0);
        }
        .sidebar-footer {
            position: absolute;
            bottom: 0;
            width: 100%;
        }
        .main-content {
            margin-left: 0 !important;
            padding: 20px 10px;
            transition: margin-left 0.3s ease;
        }
        #sidebarToggle {
            display: block;
            position: fixed;
            top: 15px;
            left: 15px;
            z-index: 1100;
            background-color: var(--sidebar-bg);
            border: none;
            padding: 8px 12px;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0,0,0,0.2);
            cursor: pointer;
        }
    }
    @media (min-width: 992px) {
        .sidebar {
            position: fixed;
            top: 0;
            left: 0;
            height: 100vh;
            width: 250px;
            background-color: var(--sidebar-bg);
            border-right: 1px solid var(--border-color);
            display: flex;
            flex-direction: column;
            transform: none !important;
        }
        .main-content {
            margin-left: 250px;
            padding: 30px;
        }
        #sidebarToggle {
            display: none;
        }
    }

    /* Action buttons improvements */
    .table td .btn-group {
        display: flex;
        flex-wrap: wrap;
        gap: 8px;
        align-items: center;
    }

    .table td .btn-group .btn {
        padding: 8px 12px !important;
        margin: 0 !important;
        border-radius: 6px !important;
        min-width: 40px;
        height: 38px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        font-size: 0.9rem;
        transition: all 0.2s ease;
        border-width: 2px;
    }

    .table td .btn-group .btn i {
        font-size: 1rem;
    }

    .table td .btn-group .btn:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
    }

    .table td .btn-outline-info {
        border-color: #0dcaf0;
        color: #0dcaf0;
    }

    .table td .btn-outline-info:hover {
        background-color: #0dcaf0;
        color: #000;
    }

    .table td .btn-outline-primary {
        border-color: #0d6efd;
        color: #0d6efd;
    }

    .table td .btn-outline-primary:hover {
        background-color: #0d6efd;
        color: #fff;
    }

    .table td .btn-outline-success {
        border-color: #198754;
        color: #198754;
    }

    .table td .btn-outline-success:hover {
        background-color: #198754;
        color: #fff;
    }

    /* Dark mode improvements for action buttons */
    html[data-theme="dark"] .table td .btn-outline-info,
    [data-theme="dark"] .table td .btn-outline-info {
        border-color: #0dcaf0;
        color: #0dcaf0;
    }

    html[data-theme="dark"] .table td .btn-outline-info:hover,
    [data-theme="dark"] .table td .btn-outline-info:hover {
        background-color: #0dcaf0;
        color: #000;
    }

    html[data-theme="dark"] .table td .btn-outline-primary,
    [data-theme="dark"] .table td .btn-outline-primary {
        border-color: #4e9eff;
        color: #4e9eff;
    }

    html[data-theme="dark"] .table td .btn-outline-primary:hover,
    [data-theme="dark"] .table td .btn-outline-primary:hover {
        background-color: #4e9eff;
        color: #fff;
    }

    html[data-theme="dark"] .table td .btn-outline-success,
    [data-theme="dark"] .table td .btn-outline-success {
        border-color: #4caf50;
        color: #4caf50;
    }

    html[data-theme="dark"] .table td .btn-outline-success:hover,
    [data-theme="dark"] .table td .btn-outline-success:hover {
        background-color: #4caf50;
        color: #fff;
    }
    </style>
</head>
<body>

<button id="sidebarToggle" aria-label="Toggle sidebar">
    <i class="fas fa-bars"></i>
</button>

<!-- Sidebar -->
<div class="sidebar" id="sidebar">
    <div class="sidebar-header">
        <img src="icons/Logo.png" alt="Water Billing Logo" class="img-fluid" style="max-height: 90px;" />
    </div>
    
    <div class="nav-content">
        <a href="adminlandingpage.php">
            <i class="fas fa-chart-line"></i>
            <span>Billing Dashboard</span>
        </a>
        <a href="view_clients.php">
            <i class="fas fa-users"></i>
            <span>Customers</span>
        </a>
        <a href="billing_list.php">
            <i class="fas fa-file-invoice-dollar"></i>
            <span>Bills</span>
        </a>
        <a href="pending_readings.php">
            <i class="fas fa-camera"></i>
            <span>Meter Readings</span>
        </a>
        <a href="payments.php">
            <i class="fas fa-money-bill-wave"></i>
            <span>Payments</span>
        </a>
        <a href="customer_accounts.php">
            <i class="fas fa-user-circle"></i>
            <span>Customer Accounts</span>
        </a>
        <a href="reports.php">
            <i class="fas fa-chart-line"></i>
            <span>Reports</span>
        </a>
        <a href="client_reports.php">
            <i class="fas fa-chart-bar"></i>
            <span>Water Outage Reports</span>
        </a>
        <a href="disconnection_notices.php" class="active">
            <i class="fas fa-exclamation-triangle"></i>
            <span>Disconnection Notices</span>
        </a>
        <a href="settings_rate.php">
            <i class="fas fa-cog"></i>
            <span>Settings</span>
        </a>
    </div>

    <div class="sidebar-footer">
        <!-- Theme Switch -->
        <div class="theme-switch-wrapper">
            <i class="fas fa-sun"></i>
            <label class="theme-switch">
                <input type="checkbox" id="theme-toggle">
                <span class="slider"></span>
            </label>
            <i class="fas fa-moon"></i>
        </div>
        
        <form method="POST" action="logout.php" class="mt-3">
            <button type="submit" class="btn btn-outline-primary w-100">
                <i class="fas fa-sign-out-alt me-2"></i>
                Logout
            </button>
        </form>
    </div>
</div>

<!-- Main Content -->
<div class="main-content">
    <!-- Success/Error Messages -->
    <?php if ($success_message): ?>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="fas fa-check-circle me-2"></i><?php echo $success_message; ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    <?php endif; ?>

    <?php if ($error_message): ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <i class="fas fa-exclamation-circle me-2"></i><?php echo $error_message; ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    <?php endif; ?>

    <!-- Page Header -->
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h2 class="mb-0">
                <i class="fas fa-exclamation-triangle text-warning me-2"></i>
                Disconnection Notices
            </h2>
            <p class="text-muted mt-2">Manage water service disconnection notices for overdue accounts</p>
        </div>
        <div>
            <button type="button" class="btn btn-warning me-2" data-bs-toggle="modal" data-bs-target="#autoGenerateModal">
                <i class="fas fa-magic me-1"></i>Auto Generate
            </button>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#manualNoticeModal">
                <i class="fas fa-plus me-1"></i>Create Manual Notice
            </button>
        </div>
    </div>

    <!-- Statistics Cards -->
    <div class="row mb-4">
        <div class="col-md-3">
            <div class="card card-soft stat-card pending">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="card-subtitle mb-1 text-muted">Pending Notices</h6>
                            <h4 class="card-title mb-0"><?php echo $stats['pending_notices']; ?></h4>
                        </div>
                        <i class="fas fa-clock fa-2x text-warning"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-soft stat-card sent">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="card-subtitle mb-1 text-muted">Sent Notices</h6>
                            <h4 class="card-title mb-0"><?php echo $stats['sent_notices']; ?></h4>
                        </div>
                        <i class="fas fa-paper-plane fa-2x text-primary"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-soft stat-card critical">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="card-subtitle mb-1 text-muted">Critical Notices</h6>
                            <h4 class="card-title mb-0"><?php echo $stats['critical_notices']; ?></h4>
                            <small class="text-muted">Disconnection Orders</small>
                        </div>
                        <i class="fas fa-exclamation-circle fa-2x text-danger"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-soft stat-card resolved">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h6 class="card-subtitle mb-1 text-muted">Total Amount Due</h6>
                            <h4 class="card-title mb-0">₱<?php echo number_format((float)($stats['total_amount_due'] ?? 0), 2); ?></h4>
                        </div>
                        <i class="fas fa-peso-sign fa-2x text-success"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Filters -->
    <div class="card card-soft filters-card mb-4">
        <div class="card-body">
            <form method="GET" class="row g-3">
                <div class="col-md-3">
                    <label for="status" class="form-label">Status</label>
                    <select class="form-select" id="status" name="status">
                        <option value="">All Status</option>
                        <option value="pending" <?php echo $status_filter === 'pending' ? 'selected' : ''; ?>>Pending</option>
                        <option value="sent" <?php echo $status_filter === 'sent' ? 'selected' : ''; ?>>Sent</option>
                        <option value="acknowledged" <?php echo $status_filter === 'acknowledged' ? 'selected' : ''; ?>>Acknowledged</option>
                        <option value="resolved" <?php echo $status_filter === 'resolved' ? 'selected' : ''; ?>>Resolved</option>
                        <option value="expired" <?php echo $status_filter === 'expired' ? 'selected' : ''; ?>>Expired</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label for="type" class="form-label">Notice Type</label>
                    <select class="form-select" id="type" name="type">
                        <option value="">All Types</option>
                        <option value="first_warning" <?php echo $type_filter === 'first_warning' ? 'selected' : ''; ?>>First Warning</option>
                        <option value="final_notice" <?php echo $type_filter === 'final_notice' ? 'selected' : ''; ?>>Final Notice</option>
                        <option value="disconnection_order" <?php echo $type_filter === 'disconnection_order' ? 'selected' : ''; ?>>Disconnection Order</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label for="billing_cycle_id" class="form-label">Billing Cycle</label>
                    <select class="form-select" id="billing_cycle_id" name="billing_cycle_id">
                        <option value="0">All Billing Cycles</option>
                        <?php if ($billing_cycles && $billing_cycles->num_rows > 0): ?>
                            <?php while ($cycle = $billing_cycles->fetch_assoc()): ?>
                                <option value="<?php echo $cycle['id']; ?>" <?php echo $billing_cycle_filter === (int)$cycle['id'] ? 'selected' : ''; ?>>
                                    <?php echo htmlspecialchars($cycle['cycle_name']); ?> 
                                    (<?php echo date('M d', strtotime($cycle['start_date'])); ?> - <?php echo date('M d, Y', strtotime($cycle['end_date'])); ?>)
                                </option>
                            <?php endwhile; ?>
                        <?php endif; ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <label for="search" class="form-label">Search Client</label>
                    <input type="text" class="form-control" id="search" name="search" value="<?php echo htmlspecialchars($search); ?>" placeholder="Name or Client Code">
                </div>
                <div class="col-md-2 d-flex align-items-end">
                    <button type="submit" class="btn btn-primary me-2">
                        <i class="fas fa-search me-1"></i>Apply Filters
                    </button>
                    <a href="disconnection_notices.php" class="btn btn-outline-secondary">
                        <i class="fas fa-sync-alt me-1"></i>Reset
                    </a>
                </div>
            </form>
        </div>
    </div>

    <!-- Notices Table -->
    <div class="card card-soft">
        <div class="card-header">
            <h5 class="card-title mb-0">
                <i class="fas fa-list me-2"></i>Disconnection Notices
            </h5>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead>
                        <tr>
                            <th>Client</th>
                            <th>Notice Type</th>
                            <th>Amount Due</th>
                            <th>Overdue Days</th>
                            <th>Disconnection Date</th>
                            <th>Status</th>
                            <th>Created</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($notices && $notices->num_rows > 0): ?>
                            <?php while ($notice = $notices->fetch_assoc()): ?>
                            <tr class="<?php 
                                    echo $notice['status'] === 'pending' ? 'notice-row-pending' : 
                                        ($notice['status'] === 'sent' ? 'notice-row-sent' : 
                                        ($notice['status'] === 'resolved' ? 'notice-row-resolved' : 'notice-row-expired'));
                                ?>">
                                <td>
                                    <div>
                                        <strong><?php echo htmlspecialchars($notice['firstname'] . ' ' . $notice['lastname']); ?></strong>
                                        <br><small class="text-muted"><?php echo htmlspecialchars($notice['client_code']); ?></small>
                                    </div>
                                </td>
                                <td>
                                    <span class="badge <?php 
                                        echo $notice['notice_type'] === 'first_warning' ? 'bg-warning' : 
                                            ($notice['notice_type'] === 'final_notice' ? 'bg-danger' : 'bg-dark');
                                    ?>">
                                        <?php echo ucfirst(str_replace('_', ' ', $notice['notice_type'])); ?>
                                    </span>
                                </td>
                                <td>
                                    <strong>₱<?php echo number_format($notice['amount_due'], 2); ?></strong>
                                </td>
                                <td>
                                    <span class="badge bg-<?php echo $notice['overdue_days'] > 90 ? 'danger' : ($notice['overdue_days'] > 60 ? 'warning' : 'info'); ?>">
                                        <?php echo $notice['overdue_days']; ?> days
                                    </span>
                                </td>
                                <td>
                                    <?php if ($notice['disconnection_date']): ?>
                                        <strong class="text-danger">
                                            <?php echo date('M j, Y', strtotime($notice['disconnection_date'])); ?>
                                        </strong>
                                    <?php else: ?>
                                        <span class="text-muted">-</span>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <span class="badge bg-<?php 
                                        echo $notice['status'] === 'pending' ? 'warning' : 
                                            ($notice['status'] === 'sent' ? 'primary' : 
                                            ($notice['status'] === 'resolved' ? 'success' : 'secondary'));
                                    ?>">
                                        <?php echo ucfirst($notice['status']); ?>
                                    </span>
                                </td>
                                <td>
                                    <div>
                                        <?php echo date('M j, Y', strtotime($notice['created_at'])); ?>
                                        <br><small class="text-muted">by <?php echo htmlspecialchars($notice['created_by_username']); ?></small>
                                    </div>
                                </td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <button type="button" class="btn btn-sm btn-outline-info" 
                                                onclick="viewNotice(<?php echo $notice['id']; ?>)">
                                            <i class="fas fa-eye"></i>
                                        </button>
                                        <?php if ($notice['status'] === 'pending'): ?>
                                            <form method="POST" style="display: inline; margin: 0;">
                                                <input type="hidden" name="action" value="send_notice">
                                                <input type="hidden" name="notice_id" value="<?php echo $notice['id']; ?>">
                                                <button type="submit" class="btn btn-sm btn-outline-primary" 
                                                        onclick="return confirm('Send this notice?')">
                                                    <i class="fas fa-paper-plane"></i>
                                                </button>
                                            </form>
                                        <?php endif; ?>
                                        <?php if (in_array($notice['status'], ['sent', 'acknowledged'])): ?>
                                            <button type="button" class="btn btn-sm btn-outline-success" 
                                                    onclick="resolveNotice(<?php echo $notice['id']; ?>)">
                                                <i class="fas fa-check"></i>
                                            </button>
                                        <?php endif; ?>
                                    </div>
                                </td>
                            </tr>
                            <?php endwhile; ?>
                        <?php else: ?>
                        <tr>
                            <td colspan="8" class="text-center py-4 text-muted">
                                <i class="fas fa-info-circle me-2"></i>No disconnection notices found
                            </td>
                        </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Auto Generate Modal -->
<div class="modal fade" id="autoGenerateModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    <i class="fas fa-magic me-2"></i>Auto Generate Disconnection Notices
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="alert alert-info">
                    <i class="fas fa-info-circle me-2"></i>
                    This will automatically generate disconnection notices for all eligible clients based on their overdue bills.
                </div>
                
                <h6>Clients who will receive notices<?php echo $billing_cycle_filter ? ' for selected billing cycle' : ''; ?>:</h6>
                <div class="table-responsive">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>Client</th>
                                <th>Notice Type</th>
                                <th>Reason</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (!empty($clients_needing_notices)): ?>
                                <?php foreach ($clients_needing_notices as $client): ?>
                                    <?php foreach ($client['notices_needed'] as $notice): ?>
                                    <tr>
                                        <td><?php echo htmlspecialchars($client['firstname'] . ' ' . $client['lastname']); ?></td>
                                        <td>
                                            <span class="badge bg-<?php echo $notice['type'] === 'first_warning' ? 'warning' : ($notice['type'] === 'final_notice' ? 'danger' : 'dark'); ?>">
                                                <?php echo ucfirst(str_replace('_', ' ', $notice['type'])); ?>
                                            </span>
                                        </td>
                                        <td><?php echo htmlspecialchars($notice['reason']); ?></td>
                                    </tr>
                                    <?php endforeach; ?>
                                <?php endforeach; ?>
                            <?php else: ?>
                            <tr>
                                <td colspan="3" class="text-center text-muted">No clients currently need disconnection notices</td>
                            </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <?php if (!empty($clients_needing_notices)): ?>
                    <form method="POST" style="display: inline;">
                        <input type="hidden" name="action" value="auto_generate">
                        <input type="hidden" name="billing_cycle_id" value="<?php echo (int)$billing_cycle_filter; ?>">
                        <button type="submit" class="btn btn-warning">
                            <i class="fas fa-magic me-1"></i>Generate Notices
                        </button>
                    </form>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<!-- Manual Notice Modal -->
<div class="modal fade" id="manualNoticeModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    <i class="fas fa-plus me-2"></i>Create Manual Disconnection Notice
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form method="POST">
                <div class="modal-body">
                    <input type="hidden" name="action" value="create_manual">
                    
                    <div class="mb-3">
                        <label for="client_id" class="form-label">Client *</label>
                        <select class="form-select" id="client_id" name="client_id" required>
                            <option value="">Select Client</option>
                            <?php while ($client = $clients->fetch_assoc()): ?>
                                <option value="<?php echo $client['id']; ?>">
                                    <?php echo htmlspecialchars($client['firstname'] . ' ' . $client['lastname'] . ' (' . $client['code'] . ')'); ?>
                                </option>
                            <?php endwhile; ?>
                        </select>
                    </div>
                    
                    <div class="mb-3">
                        <label for="notice_type" class="form-label">Notice Type *</label>
                        <select class="form-select" id="notice_type" name="notice_type" required>
                            <option value="first_warning">First Warning</option>
                            <option value="final_notice">Final Notice</option>
                            <option value="disconnection_order">Disconnection Order</option>
                        </select>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="amount_due" class="form-label">Amount Due *</label>
                                <input type="number" class="form-control" id="amount_due" name="amount_due" step="0.01" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="overdue_days" class="form-label">Overdue Days *</label>
                                <input type="number" class="form-control" id="overdue_days" name="overdue_days" required>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mb-3">
                        <label for="due_date" class="form-label">Original Due Date *</label>
                        <input type="date" class="form-control" id="due_date" name="due_date" required>
                    </div>
                    
                    <div class="mb-3">
                        <label for="custom_description" class="form-label">Custom Description (Optional)</label>
                        <textarea class="form-control" id="custom_description" name="custom_description" rows="4" 
                                  placeholder="Leave blank to use standard notice template"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-plus me-1"></i>Create Notice
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- View Notice Modal -->
<div class="modal fade" id="viewNoticeModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    <i class="fas fa-eye me-2"></i>Notice Details
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body" id="noticeDetailsContent">
                <!-- Content loaded via JavaScript -->
            </div>
        </div>
    </div>
</div>

<!-- Resolve Notice Modal -->
<div class="modal fade" id="resolveNoticeModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    <i class="fas fa-check me-2"></i>Resolve Notice
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form method="POST">
                <div class="modal-body">
                    <input type="hidden" name="action" value="resolve_notice">
                    <input type="hidden" name="notice_id" id="resolveNoticeId">
                    
                    <div class="mb-3">
                        <label for="resolution_notes" class="form-label">Resolution Notes *</label>
                        <textarea class="form-control" id="resolution_notes" name="resolution_notes" rows="4" 
                                  placeholder="Explain how this notice was resolved..." required></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">
                        <i class="fas fa-check me-1"></i>Mark as Resolved
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    const themeToggle = document.getElementById('theme-toggle');
    const html = document.documentElement;
    
    const savedTheme = localStorage.getItem('theme') || 'light';
    html.setAttribute('data-theme', savedTheme);
    themeToggle.checked = savedTheme === 'dark';

    themeToggle.addEventListener('change', function() {
        const theme = this.checked ? 'dark' : 'light';
        html.setAttribute('data-theme', theme);
        localStorage.setItem('theme', theme);
    });

    // Auto-submit filter form when Status or Notice Type dropdowns change
    const statusSelect = document.getElementById('status');
    const typeSelect = document.getElementById('type');
    const filterForm = statusSelect ? statusSelect.closest('form') : null;

    if (statusSelect && filterForm) {
        statusSelect.addEventListener('change', function() {
            filterForm.submit();
        });
    }

    if (typeSelect && filterForm) {
        typeSelect.addEventListener('change', function() {
            filterForm.submit();
        });
    }
});

// Sidebar toggle for mobile
document.addEventListener('DOMContentLoaded', function() {
    var sidebar = document.getElementById('sidebar');
    var sidebarToggle = document.getElementById('sidebarToggle');
    if (sidebarToggle) {
        sidebarToggle.addEventListener('click', function() {
            sidebar.classList.toggle('open');
        });
    }
    document.addEventListener('click', function(e) {
        if (window.innerWidth <= 991 && sidebar.classList.contains('open')) {
            if (!sidebar.contains(e.target) && e.target !== sidebarToggle) {
                sidebar.classList.remove('open');
            }
        }
    });
});

function viewNotice(noticeId) {
    // Load notice details via AJAX
    fetch(`get_disconnection_notice.php?id=${noticeId}`)
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                const notice = data.notice;
                document.getElementById('noticeDetailsContent').innerHTML = `
                    <div class="row">
                        <div class="col-md-6">
                            <h6>Client Information</h6>
                            <p><strong>Name:</strong> ${notice.client_name}</p>
                            <p><strong>Contact:</strong> ${notice.contact}</p>
                            <p><strong>Address:</strong> ${notice.address}</p>
                        </div>
                        <div class="col-md-6">
                            <h6>Notice Details</h6>
                            <p><strong>Type:</strong> ${notice.notice_type}</p>
                            <p><strong>Amount Due:</strong> ₱${parseFloat(notice.amount_due).toLocaleString()}</p>
                            <p><strong>Overdue Days:</strong> ${notice.overdue_days}</p>
                            <p><strong>Status:</strong> ${notice.status}</p>
                        </div>
                    </div>
                    <hr>
                    <h6>Notice Content</h6>
                    <h5>${notice.title}</h5>
                    <div style="white-space: pre-line;">${notice.description}</div>
                `;
                new bootstrap.Modal(document.getElementById('viewNoticeModal')).show();
            }
        })
        .catch(error => console.error('Error:', error));
}

function resolveNotice(noticeId) {
    document.getElementById('resolveNoticeId').value = noticeId;
    new bootstrap.Modal(document.getElementById('resolveNoticeModal')).show();
}
</script>
</body>
</html> 